services:
  app:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ..:/workspaces/my-data-prep
    command: sleep infinity
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: datawarehouse
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db-scripts:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
